// Targeted by JavaCPP version unknown: DO NOT EDIT THIS FILE

package my;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;
import static org.bytedeco.javacpp.opencv_imgcodecs.*;
import static org.bytedeco.javacpp.opencv_videoio.*;
import static org.bytedeco.javacpp.opencv_highgui.*;
import static org.bytedeco.javacpp.caffe.*;

// The following code has been generated by JavaCPP.

public class test extends my.presets.test {
    static { Loader.load(); }

// Parsed from test.hpp

// #ifndef TEST_HPP
// #define TEST_HPP

// #include "caffe/caffe.hpp"

@Namespace("test") public static class Test extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public Test() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public Test(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Test(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public Test position(long position) {
        return (Test)super.position(position);
    }

  public native @StdString BytePointer test();
}



// #endif


}
